services:
  - type: web
    name: your-service-name
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps
    startCommand: node index.js
    aptPackages:
      - chromium-browser

    envVars:
      - key: PORT
        value: 10000
