services:
  - type: web
    name: caa-checker
    env: node
    plan: free
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y chromium-browser
      npm install --legacy-peer-deps
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 10000
